--- #YAML:1.0
name: WWW-Mechanize-Timed
version: 0.42
license: perl
distribution_type: module
requires:
  LWPx::TimedHTTP: 1.2
  Test::More: 0.01
  WWW::Mechanize: 0.72
recommends: {}
build_requires: {}
conflicts: {}
provides:
  WWW::Mechanize::Timed:
    file: lib/WWW/Mechanize/Timed.pm
    version: 0.42
generated_by: Module::Build version 0.21
