--- #YAML:1.0
name:                WWW-Mechanize-Timed
version:             0.44
abstract:            ~
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWPx::TimedHTTP:               1.2
    Test::More:                    0.01
    WWW::Mechanize:                0.72
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
